name: Circle the Sun
favicon: null
layout_spectrum: 0.73842
typography_spectrum: 0.99655
title: Circle the Sun Books
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefdf9'
    - '#c2cbd1'
    - '#5e5f4c'
    - '#9a9798'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
