name: Circle the Sun
favicon: null
layout_spectrum: 0.50207
typography_spectrum: 0.99655
title: A Fantasy Quadrology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fafafa'
    - '#fbfbfb'
    - '#fcfcfc'
    - '#fefefe'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
