name: Circle the Sun
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bdc28a'
    - '#9aa161'
    - '#535f29'
    - '#e0e4be'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
