name: Circle the Sun
favicon: null
layout_spectrum: 0.4985590938013047
typography_spectrum: 0.01678773877210915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bac1c4'
    - '#010101'
    - '#d0dde4'
    - '#5c5d4a'
    - '#939389'
  brandStrength: 0.8452493958175182
  lightness: 0.3125
  saturation: 0.3287525433115661
  rhythmicContrast: 0.5
purpose: []
